/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useState } from 'react';
import type { Comment } from '../types/comment';

interface CommentFormProps {
  onSubmit: (content: Comment, files?: File[]) => void;
  placeholder?: string;
  ticketID: string; // Added ticketID prop
}

export function CommentForm({ onSubmit, placeholder = "Add a comment...", ticketID }: CommentFormProps) {
  const [text, setText] = useState<string>(''); // Use text for the input value
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [attachments, setAttachments] = useState<File[]>([]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!text.trim() && attachments.length === 0) return;

    setIsSubmitting(true);

    try {
      // Create a Comment object from the input text
      const comment: Comment = {
        id: '', // This would typically be generated by the backend
        content: text.trim(),
        createdAt: new Date().toISOString(),
        createdBy: 'current.user@company.com', // TODO: Replace with actual user name
        modifiedAt: new Date().toISOString(), // or null if allowed
        ticketId: ticketID, // Use ticketID from props
        // Add other required properties based on your Comment type
      };
      
      await onSubmit(comment, attachments.length > 0 ? attachments : undefined);
      console.log('Comment submitted:', comment, attachments);

      setText('');
      setAttachments([]);
    } catch (error) {
      console.error('Failed to submit comment:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
      e.preventDefault();
      handleSubmit(e as any);
    }
  };

 const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      // Convert FileList to Array and append to existing attachments
      const newFiles = Array.from(files);
      setAttachments(prev => [...prev, ...newFiles]);
      
      // Reset the file input so the same files can be selected again
      e.target.value = '';
    }
  };

    const removeAttachment = (index: number) => {
    setAttachments(prev => prev.filter((_, i) => i !== index));
  };

   return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="flex space-x-4">
        <div className="flex-shrink-0 pt-2">
          <div className="w-8 h-8 bg-gradient-to-br from-green-500 to-blue-600 rounded-full flex items-center justify-center text-white font-semibold text-sm">
            U
          </div>
        </div>

        <div className="flex-1">
          <div className="relative">
            <textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder={placeholder}
              rows={3}
              className="text-gray-90 w-full px-4 py-3 border border-gray-300 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent placeholder-gray-40 text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={isSubmitting}
            />

            <div className="absolute bottom-2 right-2 text-xs text-gray-40">
              {text.length}/10000
            </div>
          </div>

          {/* Attachments preview */}
          {attachments.length > 0 && (
            <div className="mt-3 space-y-2 ">
              <p className="text-xs text-gray-50 font-medium">Attachments ({attachments.length})</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {attachments.map((file, index) => (
                  <div 
                    key={`${file.name}-${index}`}
                    className="bg-gray-800 rounded-lg p-2 flex items-center justify-between"
                  >
                    <div className="flex items-center space-x-2 flex-1 min-w-0">
                      <svg className="w-5 h-5 text-gray-50 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clipRule="evenodd" />
                      </svg>
                      <span className="text-sm text-gray-70 truncate">{file.name}</span>
                      <span className="text-xs text-gray-50 flex-shrink-0">({(file.size / 1024).toFixed(1)} KB)</span>
                    </div>
                    <button 
                      type="button" 
                      onClick={() => removeAttachment(index)}
                      className="text-gray-400 hover:text-gray-60 ml-2 flex-shrink-0"
                    >
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Form actions */}
          <div className="flex items-center justify-between mt-3">
            <div className="flex items-center space-x-4">
              {/* Multiple file attachment button */}
              <div className="flex items-center space-x-2">
                <label htmlFor="file-upload" className="cursor-pointer text-gray-50 hover:text-gray-300">
                  <div className="flex items-center">
                    <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" />
                    </svg>
                    <span className="text-xs bg">
                      {attachments.length > 0 ? `${attachments.length} files` : 'Attach files'}
                    </span>
                  </div>
                </label>
                <input
                  id="file-upload"
                  type="file"
                  className="hidden"
                  onChange={handleFileChange}
                  disabled={isSubmitting}
                  multiple
                />
              </div>

              <div className="text-xs text-gray-40">
                Cmd+Enter to submit
              </div>
            </div>
            
            <div className="flex items-center space-x-3">
              <button
                type="button"
                onClick={() => {
                  setText('');
                  setAttachments([]);
                }}
                className="text-gray-50 hover:text-gray-40 text-sm transition-colors"
                disabled={isSubmitting || (!text.trim() && attachments.length === 0)}
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting || (!text.trim() && attachments.length === 0)}
                className="bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                {isSubmitting ? (
                  <div className="flex items-center space-x-2">
                    <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                    </svg>
                    <span>Posting...</span>
                  </div>
                ) : (
                  attachments.length > 0 ? `Comment with ${attachments.length} attachment${attachments.length > 1 ? 's' : ''}` : 'Comment'
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  );
}